name: Deploy to GitHub Pages

permissions:
  contents: write  # This grants write permissions to the GitHub Actions workflow
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Publish Blazor WebAssembly
        run: |
          dotnet publish MattDash.csproj -c Release -o release/wwwroot
          mkdir -p release/wwwroot
          cp bin/Release/net9.0/wwwroot/* release/wwwroot/ || true
          cp bin/Release/net9.0/wwwroot/index.html release/wwwroot/404.html || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
          publish_branch: gh-pages
          force_orphan: true