name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Publish Blazor WebAssembly
        run: |
          dotnet publish -c Release -o release/wwwroot

      - name: Prepare deployment files
        run: |
          mkdir -p release/deploy
          cp -R release/wwwroot/wwwroot/* release/deploy/
          cp release/wwwroot/web.config release/deploy/ || true
          cp release/wwwroot/MattDash.staticwebassets.endpoints.json release/deploy/ || true

      - name: List deployed files
        run: |
          echo "Listing files in release/deploy:"
          ls -la release/deploy
          echo "\nChecking index.html:"
          cat release/deploy/index.html | grep -i "base href"

      - name: Create .nojekyll file
        run: touch release/deploy/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/deploy
          publish_branch: gh-pages
          force_orphan: true
