name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Publish Blazor WebAssembly
        run: |
          dotnet publish -c Release -o release/wwwroot

      - name: List published files
        run: |
          echo "Listing files in release/wwwroot:"
          ls -la release/wwwroot
          echo "\nChecking index.html:"
          cat release/wwwroot/index.html | grep -i "base href"

      - name: Create .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
          publish_branch: gh-pages
          force_orphan: true
